### PR TITLE
Solve Issue 44

### PR DESCRIPTION
**Pull request by jfsanchez91**
This little fix solve the compilation error on some Ubuntu installations
by providing the correct OpenCV headers.

### CODE REVIEW

File: src/video.c [hunk 1]
```diff
@@ -1,4 +1,4 @@
-#include <cv.h>
+#include <opencv2/videoio/videoio_c.h>
```
Comment (developersharif) [inline src/video.c:1]: Not work in ubuntu 22.4
